### ISSUE TITLE
May-survey: revise invitation message

### ISSUE THREAD

**Issue by anguschiu1** [CivicDataHK/telegram-bot-voting#17]
Revise message from 
"由於你是第一次投票，你可以邀請 10 個支持民主的朋友來投票，請複製以下訊息給你 Telegram、WhatsApp 或 Facebook 上的朋友。" to 
"由於你是第一次投票，你可以邀請 10 個**你所熟識，而且支持民主的朋友**(red and bold)來投票。請複製以下訊息給你 Telegram、WhatsApp、Line 或 Facebook Messenger上的朋友（但請不要放在公開場合，如facebook page上分享）。"

English revised version:
"Thanks for casting your vote. Now, you can simply copy the message below to invite your friends (those who you are really know and is supporting the non-establishment camp) via Telegram, WhatsApp, Line or Facebook Messenger (And please do NOT share via public domain, e.g. Facebook Page). Each link can invite a maximum of 10 different friends to vote.

**Comment by goofyz** [comment]
Changing text color is not supported by Telegram.  And bold-ing the Chinese text is not noticeable.  Will use the \`inline fixed-width code\` to style the Chinese text.

**Comment by goofyz** [comment]
Turn out that on Android Client, the \`inline fixed-width code\` is not noticeable when applying to Chinese text as well.
