### ISSUE TITLE
Suggestion: JSON input for informal_handler.php

### ISSUE THREAD

**Issue by dfpoon** [CivicDataHK/telegram-bot-voting#32]
I've studied the "**informal_handler.php**". I propose it can be modified to receive input in JSON format. I've proposed a sample JSON as follows.

Sorry that I do not know much about PHP. Modifying the source seems to be a bit too hard.

sample json:
```
{
  "Q_COUNT": 2,
  "Q1": '非正式民調第一問：若果魔童在你的選區出選立法會，你會不會投票支持他？',
  "Q1_keyboard": ['會', '不會', '考慮中', '唔想講'],
  "Q2" : "你揀左「%s」，確定？",
  "Q2_keyboard": ['✔ 確定', '❌ 選錯了'],
  "deadline": '2016-05-31 00:00:00 +08:00' 
}
```

**"handleStageQ1"** function can be generalized to handle multiple questions and answer_keyboards.
 
------

Slightly modified:
const SURVEY_RESULT = '多謝你參加！下面係 $QUESTION1 的民調結果，現時總共 %d 人揀左。';

Constants:
const NOT_AUTHORIZED = 'Please input "/start" to start';

--------

reference:
Handling JSON like a boss in PHP
http://nitschinger.at/Handling-JSON-like-a-boss-in-PHP/

JSON editor online:
http://www.jsoneditoronline.org/

**Comment by goofyz** [comment]
You mean to define each question structure from a json file, so that a generalize `handleStage()` can easily process the message input?

**Comment by dfpoon** [comment]
Yup. Since JSON can specify array and string, all parameters could be
inputted in the JSON file.

However, since informal survey is simply used for engagement, I suggest
limiting questions to at most 2 stages. i.e. one parent question could have
only one child question. at this moment.

This would simplify the programming and also the interaction from the
users. We can always improve the JSON mechanism in the later stage.

在 2016年5月21日週六 17:42，Goofyz Leung <notifications@github.com> 寫道：
