### ISSUE TITLE
informal question configuration 

### ISSUE THREAD

**Issue by sunnychow** [CivicDataHK/telegram-bot-voting#34]
@goofyz : So we decide to store the "informal question" in json, sent to it by Telegram?

@sunnychow: 
We don't have finalize decision yet. 
But I don't think it is a good idea to send a config to Telegram bot directly. 
I suggest to do it in this way: 
We could edit the survey on Google spreadsheet (so people could edit it easily)
and then we could implement a script for converting google spreadsheet file to JSON
Save the JSON in DB as a string

At the bot side, we lookup the config from DB directly. 
But it may slow, to solve that
We could cache the JSON in redis.

**Comment by sunnychow** [comment]
to @goofyz : Will we apply the configuration for formal survey ?

**Comment by sunnychow** [comment]
![image](https://cloud.githubusercontent.com/assets/6318765/15455200/7d7f7e88-2080-11e6-858f-50f9947750f5.png)
![image](https://cloud.githubusercontent.com/assets/6318765/15455202/8234a5f2-2080-11e6-8e90-bf6f5404c361.png)

**Comment by goofyz** [comment]
When the program support flow control (skipping some questions or go back to previous one), it will be the time for "formal survey" to switch to.

**Comment by goofyz** [comment]
KY Poon, [23.05.16 08:23]
I can hard code the json if the structure is fixed. Btw, it can be simple as shown in the following link:

KY Poon, [23.05.16 08:23]
Exporting a Google Spreadsheet as JSON
http://blog.pamelafox.org/2013/06/exporting-google-spreadsheet-as-json.html?m=1

Dickan Fong, [23.05.16 08:34]
[In reply to Sunny Chow]
For #1, we need to cater the conversion from Google Spreadsheet to JSON.  Any plan?

Goofyz, [23.05.16 09:26]
I think the original intention of using json is the easiness to create a new set of questions.  Allowing non-tech user to create a bot will be super-nice, but is not the top priority.  We can always help them to create the require json in a short period of time.  After all, a real-time-create-new-survey function is not required.   Let's finish developing the json-config bot first.

We should confirm the json format(or whatever we choose to use), the config reading mechanism, saving and exporting the survey results.
