### ISSUE TITLE
Hide up selected choice when displaying second choice

### ISSUE THREAD

**Issue by anguschiu1** [CivicDataHK/telegram-bot-voting#39]
![img_7196](https://cloud.githubusercontent.com/assets/8407433/15676469/e1e7fa18-2778-11e6-931e-8e1fe6a53ddb.jpg)

Suggest hide up selected choice when displaying second choice customised keyboard, so as to avoid the selection combination as shown in image.

**Comment by goofyz** [comment]
Fixed together with #42
